### ISSUE TITLE
[FEAT] 회원 가입 뷰

### ISSUE THREAD

**Issue by chaerin-77** [Team-Daengnyang/moneynyang-client#1]
### 작업 개요
-  회원 가입 화면 플로우 구현

### 작업 내용
- Figma의 회원 가입 플로우에 따라 뷰 구현

### Todo list
- [x] 소셜 로그인 화면 구현
- [x] 회원 정보 입력 화면 구현
- [x] 계좌 커버 커스텀 화면 구현
- [x] 반려 동물 정보 입력 화면 구현
- [ ] 마이 비밀번호 화면 구현
